name: PR Checker

on:
  pull_request:
    branches: [develop, master]
    types: [synchronize, opened, reopened, edited, labeled, unlabeled]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout branch'
        uses: actions/checkout@v2

      - name: PR Checker
        uses: ./.github/actions/pr-checker
        id: pull-request
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          echo ${{ steps.pull-request.outputs.pull-request }}

      # - name: 'Open an Issue'
      #   uses: ./.github/actions/open-issue
      #   id: issue
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     title: Some title
      #     body: Some body
      #     assignees: 'elviocb,elviogithub'
      # - run: |
      #     echo ${{ steps.issue.outputs.issue }}

      # - name: 'Say hello'
      #   uses: ./.github/actions/hello
      #   id: hello
      #   with:
      #     who-to-greet: World
      # - run: |
      #     echo 'Time: ${{ steps.hello.outputs.time }}'
      #     echo $HELLO
